name: "Build, Test, Deploy Master"
on:
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Yarn Install
        run: yarn install --frozen-lockfile
        env:
          CI: "true"
      - name: Yarn Build
        run: yarn build
      - name: Sync S3
        uses: jakejarvis/s3-sync-action@7be4dc1bb3f15779950aa151741066700c886545
        with:
          args: --exclude '.git*/*' --delete --follow-symlinks
        env:
          SOURCE_DIR: "./public"
          DEST_DIR: "docs"
          AWS_REGION: "us-east-1"
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Invalidate Cloudfront Cache
        uses: chetan/invalidate-cloudfront-action@ebe6fbf6eaa6be59bc9677b705205e76069ce22b
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
